---
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

network_objects:
  - name: APP2_NET
    value: 10.20.20.0/24
    type: Network
    description: Sample object created from Ansible
