---
# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0
collections:
  - name: cisco.fmcansible
    version: ">=1.0.0,<2.0.0"
    source: https://galaxy.ansible.com
